services:
  - type: web
    name: grocery-web-app
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /index.html
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
